import './globals.css'
import type { Metadata } from 'next'
import localFont from '@next/font/local'
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })
const giFont400 = localFont({
  src: [
    {
      path: './fonts/G.I.-400.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/G.I.-400Italic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-giFont400'
});

const giFont530 = localFont({
  src: [
    {
      path: './fonts/G.I.-530.woff2',
      weight: '530',
      style: 'normal',
    },
    {
      path: './fonts/G.I.-530Italic.woff2',
      weight: '530',
      style: 'italic',
    },
  ],
  variable: '--font-giFont530'
});

const giFont750 = localFont({
  src: [
    {
      path: './fonts/G.I.-750.woff2',
      weight: '750',
      style: 'normal',
    },
    {
      path: './fonts/G.I.-750Italic.woff2',
      weight: '750',
      style: 'italic',
    }
  ],
  variable: '--fong-giFont750'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`clsx(${giFont400.variable}, ${giFont530.variable}, ${giFont750.variable})`}>{children}</body>
    </html>
  )
}
