import './globals.css'
import type { Metadata } from 'next'
import localFont from '@next/font/local'
//import { Inter } from 'next/font/google'

//const inter = Inter({ subsets: ['latin'] })
const giFont = localFont({
  src: [
    {
      path: './fonts/G.I.-400.woff2',
      weight: '400',
      style: 'normal',
      variable: '--font-gi400',
    },
    {
      path: './fonts/G.I.-400Italic.woff2',
      weight: '400',
      style: 'italic',
      variable: '--font-gi400Italic',
    },
    {
      path: './fonts/G.I.-530.woff2',
      weight: '530',
      style: 'normal',
      variable: '--font-gi530',
    },
    {
      path: './fonts/G.I.-530Italic.woff2',
      weight: '530',
      style: 'italic',
      variable: '--font-gi530Italic',
    },
    {
      path: './fonts/G.I.-750.woff2',
      weight: '750',
      style: 'normal',
      variable: '--font-gi750',
    },
    {
      path: './fonts/G.I.-750Italic.woff2',
      weight: '750',
      style: 'italic',
      variable: '--font-gi750Italic',
    }
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
